### ISSUE TITLE
Dose this still work?

### ISSUE THREAD

**Issue by Skreen5hot** [umeshgmrl/Unofficial-Vocabulary.com-API#1]
I have tried both calls and they are not responsive.

**Comment by umeshgmrl** [comment]
hi @Skreen5hot , yeah it is working.

you can see it here https://vocabulary.now.sh/words/goo

**Comment by umeshgmrl** [comment]
confirmed working

**Comment by Skreen5hot** [comment]
Thanks, I must not have waited long enough for it to start up.
